### ISSUE TITLE
Bugs after creating a Token

### ISSUE THREAD

**Issue by dbwebapp** [daoplays/LetsCook#147]
After passing all the steps to create a token the following message appears :
<img width="1650" alt="382103521-3b5b8022-e91d-4200-a5a8-48cef4a9e40d" src="https://github.com/user-attachments/assets/69cdfba5-1f73-4966-ac90-a81d098a3a83">

A Hard Refresh is needed to reload the page and the coin's dashboard is displayed.

**Comment by daoplays** [comment]
this has been fixed on devnet nw, will make it onto eclipse/mainnet on the next update
