### ISSUE TITLE
Display Problems on smaller screens

### ISSUE THREAD

**Issue by dbwebapp** [daoplays/LetsCook#148]
When trying to see a token description on smaller screen such as phone with dimension 765 x 741
Check it out :
<img width="340" alt="382105085-06f328dd-3ca3-40a3-b1ea-0f6b769d2518" src="https://github.com/user-attachments/assets/56b26597-f100-426c-b4da-8164d5b697d9">

the chart is Half way shown...

**Comment by daoplays** [comment]
should now be fixed n devnet, awaiting merge into eclipse/mainnet
