### ISSUE TITLE
Missing searching Bar for quick search 

### ISSUE THREAD

**Issue by dbwebapp** [daoplays/LetsCook#150]
I need a quick searching bar on the top of the tokens list so i do not need to scroll the all list to find my tokens or avoiding using CTRL+ F to search manually my token.
<img width="1394" alt="382109352-c9d70a30-3549-456c-98e6-2993603bbd0f" src="https://github.com/user-attachments/assets/e4df1103-a93e-479c-8bee-877431f0340c">

**Comment by daoplays** [comment]
this has now been added on devnet, will make it onto eclipse/mainnet on the next merge over.  thanks!
