### ISSUE TITLE
BUG UX : FAQ Link not displaying on smaller screens

### ISSUE THREAD

**Issue by dbwebapp** [daoplays/LetsCook#151]
Even if you scroll down to the bottom, the FAQ link not showing up :
<img width="716" alt="382344285-8cbeb503-55d1-41e1-adac-231351cb984b" src="https://github.com/user-attachments/assets/f4d2cdc2-ad5c-471d-bff0-f29f18cd0751">

I need to CTRL + - to see it proper..

<img width="571" alt="382344475-16275b5e-50d7-4516-b802-618595576962" src="https://github.com/user-attachments/assets/303ce39d-3aa6-4d58-9628-1ddf12961bb5">

**Comment by daoplays** [comment]
fixed on devnet, will be merged in soon to eclipse
