### ISSUE TITLE
Changing Mascott of Let's cook?

### ISSUE THREAD

**Issue by dbwebapp** [daoplays/LetsCook#152]
On Twitter : 
<img width="245" alt="Screenshot 73" src="https://github.com/user-attachments/assets/7419ab1f-df25-447a-8fe9-da5486a49a97">

On announcement : 
<img width="583" alt="Screenshot 74" src="https://github.com/user-attachments/assets/653b050b-5349-446b-a411-d5abb6582ebf">

Who is this new little Guy astronaut?

Are you planning to change the Let's cook Mascott?

**Comment by dbwebapp** [comment]
on the documentation : 
<img width="1205" alt="Screenshot 77" src="https://github.com/user-attachments/assets/9ace4b4a-9ddb-42cc-b883-d1023e9d648c">


May be we should have the same Mascot/ Logo everywhere....
right?

**Comment by daoplays** [comment]
the astronaut guy is from something to be announced soon!
