### ISSUE TITLE
Idea : new Feature While creating a token.

### ISSUE THREAD

**Issue by dbwebapp** [daoplays/LetsCook#153]
I can see that Laika token as the following smart contract address : 
<img width="1227" alt="Screenshot 76" src="https://github.com/user-attachments/assets/04fb67be-cc70-42d3-9734-da8ed51643e3">

As you can see it start with LAIKA

As a creator of a new token , i would be ready to paid an extra fees to get my smart contract address starting by the name of my coin : 
<img width="1220" alt="Screenshot 75" src="https://github.com/user-attachments/assets/e68a6cf9-cfb4-4ac6-9b36-5ff3a94a6c72">

Is it possible to add this feature?

**Comment by daoplays** [comment]
you can actually do this with the non instant launch (toggle on advanced mode), we'll discuss adding it as an option for the instant ones, but we wanted to keep things simple there

**Comment by daoplays** [comment]
an obvious solutoin is just to have "Instant" be an option in advanced mode and you can use the extra features there to to the token grind, will add this to our backlog

**Comment by daoplays** [comment]
ok, added this to devnet
