### ISSUE TITLE
Swap Joy NFT back to JOY token (Issue)

### ISSUE THREAD

**Issue by dbwebapp** [daoplays/LetsCook#182]
How i can select the one NFT i want to "burn" to get back JOY token??
<img width="1223" alt="Screenshot 180" src="https://github.com/user-attachments/assets/6b026ac8-7e09-456a-97f5-51c4e0f21ead">

As you can see on the picture, i have 2 NFTs but want to swap back to JOY a specific one, how should i do that?

Also, if i want to "burn " both at the same time, i cannot do it : 
- it does not allow me to edit the number 2 on the input

Do i need to make 2 swaps?

**Comment by BlueMoon0x69** [comment]
cannot list, error

**Comment by daoplays** [comment]
we just pushed a feature to let you do this, on the "my nfts screen" youll notice a little menu for each nft that lets you wrap or transfer
